version: '3.8'
services:
  ss-libev:
    image: teddysun/shadowsocks-libev
    restart: always
    container_name: sslibev
    environment:
      TZ: Asia/Jakarta
    ports:
      - 9000:9000
      - 9000:9000/udp
    volumes:
      - ${PWD}/etc/shadowsocks-libev:/etc/shadowsocks-libev

  ss-go:
    image: teddysun/shadowsocks-go
    restart: always
    container_name: ssgo
    environment:
      TZ: Asia/Jakarta
    ports:
      -  8388:8388
      -  8388:8388/udp
    volumes:
      - ${PWD}/etc/shadowsocks-go:/etc/shadowsocks-go

  ss-rust:
    image: teddysun/shadowsocks-rust
    restart: always
    container_name: ssrust
    environment:
      TZ: Asia/Jakarta
    ports:
      - 9090:9090
      - 9090:9090/udp
    volumes:
      - ${PWD}/etc/shadowsocks-rust:/etc/shadowsocks-rust
      
#  trojan-go:
#    image: teddysun/trojan-go
#   restart: always
#    network_mode: host
#    container_name: tr-go
#    environment:
#      TZ: Asia/Jakarta
#    volumes:
#      - ${PWD}/etc/trojan-go:/etc/trojan-go
      
